version: "3"


services:
  redis:
    image: redis
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

