# Generated by Django 3.1.7 on 2021-04-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210328_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='information_about_the_paid_salary',
            new_name='paid_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
