# Generated by Django 3.1.7 on 2021-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210408_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
