# Generated by Django 3.1.7 on 2021-04-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210409_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paid_salary',
            field=models.FloatField(verbose_name='Всего выплачено'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('СЕО', 'СЕО'), ('MD', 'Middle'), ('JR', 'Junior'), ('SR', 'Senior'), ('QA', 'QA')], default='JR', max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(verbose_name='Зарплата'),
        ),
    ]
