# Generated by Django 3.1.7 on 2021-04-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210425_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('have_access_api', 'Have access API')]},
        ),
    ]
