# Generated by Django 3.1.7 on 2021-05-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210425_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermissions',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.employee')),
            ],
            bases=('employee.employee',),
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
    ]
