# Generated by Django 3.1.7 on 2021-05-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210502_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePermissions',
        ),
    ]
